---
title: "Making a GitHub Pages Site"
subtitle: "(use arrows or click outside to navigate)"
author: "Collin Paschall"
date: "2/4/2022"
output: 
  ioslides_presentation:
    widescreen: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## References

All the material in this presentation is pulled from there sources:

[GitHub Pages](https://pages.github.com) getting started guide

[Emily Zabor's](https://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html) Creating websites in R

[De Leon and Hill's](https://rstudio4edu.github.io/rstudio4edu-book/) rstudio4edu

[RStudio and Garrett Grolemund](https://garrettgman.github.io/rmarkdown/rmarkdown_websites.html) R Markdown Websites.

These references are much more in-depth and will teach you many additional tricks.

## Before you start

Must do:

- Install R and RStudio
- Sign up for a GitHub account
- Install and set up [GitHub Desktop](https://desktop.github.com)

Good to do: 

- Review [R Markdown Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)

## Set Up GitHub

- Follow the [pages](https://pages.github.com) directions
- Create a repository in the browser called **username**.github.io
- Close the repository using the "Set up in Desktop" button

## R Studio
- Create a new project
- Create in a new folder, wherever you want
- Create a "Simple R Markdown Website"
- Save and close 
- Move the files to your local GitHub folder

## IMPORTANT

In the .yml file, insert: 

name: "collin.paschall"
**output_dir: "."**

## Edit your pages

- index.rmd: your homepage
- _site.yml: the structure of the website
- whatever other files you want

This is just an R Markdown file. Pretty much anything you can do in an R Markdown, you can do here (though no Shiny embedding).

Don't know markdown? [R Markdown Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)

## Knit and publish

- When you are done editing your R Markdown files, in the terminal type:

rmarkdown::render_site()

- Then, check and see if they worked locally
- Commit and push through GitHub desktop

## Profit!

You now know one of the nerd secret handshakes.

- Add a new page - just make a new .rmd, then and add the .html to the .yml
- Add slick icons
- Add a TOC to a page
- Embed R or Python code chunks and output

