---
format: pdf
editor: visual
---

# Collin Paschall

Center for Advanced Governmental Studies

Johns Hopkins University Krieger School of Arts and Sciences

Advanced Academic Programs

Washington, DC 20036

402-651-1733

cpaschall\[at\]jhu.edu

collin.paschall\[at\]gmail.com

## Appointments

**Interim Program Director, Data Analytics and Policy Program, Johns Hopkins University:**

Current position.

Short text containing the type of work done, results obtained, lessons learned and other remarks. Can also include lists and links:

-   First item

-   Item with [link](http://www.example.com). Links will work both in the html and pdf versions.

**Program Coordinator and Senior Lecturer, Center for Advanced Governmental Studies, Johns Hopkins University**

Also with a short description.

## Appointments

: Center of Advanced Governmental Studies, Johns Hopkins University

\*Interim Program Director, Data Analytics and Policy Program, 2022-present.

Program Coordinator and Senior Lecturer, Center for Advanced Governmental Studies, Johns Hopkins University, 2019-2022.

American Political Science Association Congressional Fellow, Office of Congressmember Karen Bass (CA-37), 2018-2019.

## Education

2010-2014 (expected)

:   **PhD, Computer Science**; Awesome University (MyTown)

    *Thesis title: Deep Learning Approaches to the Self-Awesomeness Estimation Problem*

2007-2010

:   **BSc, Computer Science and Electrical Engineering**; University of HomeTown (HomeTown)

    *Minor: Awesomeology*

## Experience

**Your Most Recent Work Experience:**

Short text containing the type of work done, results obtained, lessons learned and other remarks. Can also include lists and links:

-   First item

-   Item with [link](http://www.example.com). Links will work both in the html and pdf versions.

**That Other Job You Had**

Also with a short description.

## Technical Experience

My Cool Side Project

:   For items which don't have a clear time ordering, a definition list can be used to have named items.

    -   These items can also contain lists, but you need to mind the indentation levels in the markdown source.
    -   Second item.

Open Source

:   List open source contributions here, perhaps placing emphasis on the project names, for example the **Linux Kernel**, where you implemented multithreading over a long weekend, or **node.js** (with [link](http://nodejs.org)) which was actually totally your idea...

Programming Languages

:   **first-lang:** Here, we have an itemization, where we only want to add descriptions to the first few items, but still want to mention some others together at the end. A format that works well here is a description list where the first few items have their first word emphasized, and the last item contains the final few emphasized terms. Notice the reasonably nice page break in the pdf version, which wouldn't happen if we generated the pdf via html.

:   **second-lang:** Description of your experience with second-lang, perhaps again including a \[link\] [ref](https://github.com/githubuser/superlongprojectname), this time placing the url reference elsewhere in the document to reduce clutter (see source file).

:   **obscure-but-impressive-lang:** We both know this one's pushing it.

:   Basic knowledge of **C**, **x86 assembly**, **forth**, **Common Lisp**

## Extra Section, Call it Whatever You Want

-   Human Languages:

    -   English (native speaker)
    -   ???
    -   This is what a nested list looks like.

-   Random tidbit

-   Other sort of impressive-sounding thing you did
