---
title: "Trainings and Resources"
output: 
  html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("vembedr")
```

Periodically I will post useful resources and trainings that I either locate or make myself.

### Working with Git and GitHub

<!-- May 2022 -->

<!-- Cleaning your social media diet. -->

<!-- After Musk bought Twitter, it prompted me to reconsider my use of Twitter. I don't wish to support Musk, but I find Twitter a very useful source of information on emerging scholarship and some news sources. So, I have developed hacky workaround. -->

<!-- First, I learned how to create an RSS feed from this website. It is easy. 

Then, I set up an IFTTT account. For $10 a month, you can create unlimited applets that will send tweets to a Google Drive document. Now, I get the benefits of viewing my Twitter feed without any noise, and only the accounts I really want to see. No likes, ads, or log-ins. Musk will probably kick me off eventually. -->

<!-- https://www.makeuseof.com/tag/how-to-create-an-rss-feed-for-your-site-from-scratch/ -->

April 2022

[Git/GH Presentation Slides](./git_gh.html).

[Source Material from Karl Broman.](https://kbroman.org/github_tutorial/)

Workshop Recording:

[Link](https://www.youtube.com/watch?v=6nASVoRzBzg)

```{r,echo=FALSE}
embed_youtube("6nASVoRzBzg")
```

### Making a Website Using Github

February 2022

[Presentation Slides](./github_pres.html).

Workshop Recording:

[Link](https://www.youtube.com/watch?v=MoiAuoGb-b4)

```{r,echo=FALSE}
embed_youtube("MoiAuoGb-b4")
```
